# name: 'Readme Link Analytics Tracker'
# description: 'Action modifies all links in README.md for tracking anaylitics'
# inputs:
#   commit-message: 
#     description: 'Commit message to be used for automated updation of README.md'
#     required: false
#     default: '(Automated) Update README.md for link tracking'
# runs:
#   using: "composite"
#   steps:
#     # Reference a specific commit
#     - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
#     # Reference the major version of a release
#     - uses: actions/checkout@v3
#     # Reference a specific version
#   using: 'node16'
#   main: 'index.js'

name: 'Readme Link Analytics Tracker'
description: 'Action modifies all links in README.md for tracking anaylitics'
inputs:
  commit-message: 
    description: 'Commit message to be used for automated updation of README.md'
    required: false
    default: '(Automated) Update README.md for link tracking'
runs:
  using: "composite"
  steps:
    # Reference the major version of a release
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Substitute all links in README.md
      run: sed "s/\(\[.*\]\)(\(.*\))/\1(https:\/\/shubhamgarg.com\?url=\2)/" README.md
      shell: bash
    
    - name: Add and Commit changes
      run: git add README.md && git commit -m "(Automated) Update README.md links"
      shell: bash
