name: 'Readme Link Analytics Tracker'
description: 'Action modifies all links in README.md for tracking anaylitics'
inputs:
  branch:
    description: "The branch to checkout and commit changes"
    required: false
    default: "main"

  author_name:
    description: The name of the user that will be displayed as the author of the commit
    required: false
    default: "github-actions"

  author_email:
    description: The email of the user that will be displayed as the author of the commit
    required: false
    default: "github-actions@github.com"
  
  commit-message: 
    description: 'The commit message to be used for automated updation of README.md'
    required: false
    default: '(Automated) Update README.md for link tracking'


runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Substitute all links in README.md and commit changes
      shell: bash
      run: |
        git checkout ${INPUT_BRANCH}
        sed -i "s/\(\[.*\]\)(\(.*\))/\1(https:\/\/shubhamgarg.com\?url=\2)/" README.md
        git config user.name ${INPUT_AUTHOR_NAME}
        git config user.email ${INPUT_AUTHOR_EMAIL}
        git diff --quiet || git add README.md || git commit -m ${INPUT_COMMIT_MESSAGE} && git push
