on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Readme Link Tracking
    steps:
      - name: Modifying README.md links
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: shubhamgrg04/readme-link-analytics@v1.1
        